<?php
require_once "NewCar.php";
class CarWithExtras extends NewCar
{
protected $alarm=800;
protected $radio;
protected $ac;


    public function calculatePrice($price)
{
//    $car = new CarWithExtras();
    $price += $this->getAc();
    $price += $this->getAlarm();
    $price += $this->getRadio();

    return parent::calculatePrice($price); // TODO: Change the autogenerated stub
}



    /**
     * @return int
     */
    public function getAlarm()
    {
        return $this->alarm;
    }

    /**
     * @return int
     */
    public function getRadio()
    {
        return $this->radio;
    }

    /**
     * @return int
     */
    public function getAc()
    {
        return $this->ac;
    }

    /**
     * @param mixed $alarm
     */
    public function setAlarm($alarm)
    {
        $this->alarm = $alarm;
    }

    /**
     * @param mixed $radio
     */
    public function setRadio($radio)
    {
        $this->radio = $radio;
    }

    /**
     * @param mixed $ac
     */
    public function setAc($ac)
    {
        $this->ac = $ac;
    }


}