<?php
require_once "CarWithExtras.php";
class Insurance extends CarWithExtras
{
private $insurance = 0.01;
private $years;

public function calculatePrice($price)
{
    $price= parent::calculatePrice($price); // TODO: Change the autogenerated stub

    return ($this->insurance *($price*(100-$this->getYears())/100));
}

    /**
     * @return mixed
     */
    public function getYears()
    {
        return $this->years;
    }

    /**
     * @param mixed $years
     */
    public function setYears($years)
    {
        $this->years = $years;
    }


}