<?php
/*
 * Napisz program “jakiej jestem narodowości” z użyciem tablic asocjacyjnych.
 * Program powinien przyjmować nazwę kraju, a następnie w zawartej w nim tablicy
 * sprawdzić, jak nazywa się odpowiednia narodowość - i tę narodowość zwrócić.
 */

const NATIONALITY=[
    'Afghanistan' => 'Afghan',
    'Albania' => 'Albanian',
    'Algeria' => 'Algerian',
    'Angola' => 'Angolan',
    'Argentina' => 'Argentine',
    'Australia' => 'Australian',
    'Austria' => 'Austrian',
    'Bangladesh' => 'Bangladeshi',
    'Belgium' => 'Belgian',
    'Bolivia' => 'Bolivian',
    'Botswana' => 'Botswanan',
    'Brazil' => 'Brazilian',
    'Bulgaria' => 'Bulgarian',
    'Cambodia' => 'Cambodian',
    'Cameroon' => 'Cameroonian',
    'Canada' => 'Canadian',
    'Chile' => 'Chilean',
    'China' => 'Chinese person',
    'Colombia' => 'Colombian',
    'Costa Rica' => 'Costa Rican',
    'Croatia' => 'Croat',
    'Cuba' => 'Cuban',
    'Czech Republic' => 'Czech person',
    'Denmark' => 'Dane',
    'Dominican Republic' => 'Dominican',
    'Ecuador' => 'Ecuadorian',
    'Egypt' => 'Egyptian',
    'El Salvador' => 'Salvadoran',
    'England' => 'Englishman',
    'Estonia' => 'Estonian',
    'Ethiopia' => 'Ethiopian',
    'Fiji' => 'Fijian',
    'Finland' => 'Finn',
    'France' => 'Frenchman',
    'Germany' => 'German',
    'Ghana' => 'Ghanaian',
    'Greece' => 'Greek',
    'Guatemala' => 'Guatemalan',
    'Haiti' => 'Haitian',
    'Holland' => 'Dutchman',
    'Honduras' => 'Honduran',
    'Hungary' => 'Hungarian',
    'Iceland' => 'Icelander',
    'India' => 'Indian',
    'Indonesia' => 'Indonesian',
    'Iran' => 'Iranian',
    'Iraq' => 'Iraqi',
    'Ireland' => 'Irishman',
    'Israel' => 'Israeli',
    'Italy' => 'Italian',
    'Jamaica' => 'Jamaican',
    'Japan' => 'Japanese person',
    'Jordan' => 'Jordanian',
    'Kazakhstan' => 'Kazakhstani',
    'Kenya' => 'Kenyan',
    'Kuwait' => 'Kuwaiti',
    'Laos' => 'Laotian',
    'Latvia' => 'Latvian',
    'Lebanon' => 'Lebanese',
    'Libya' => 'Libyan',
    'Lithuania' => 'Lithuanian',
    'Malaysia' => 'Malaysian',
    'Mali' => 'Malian',
    'Malta' => 'Maltese',
    'Mauritania' => 'Mauritanian',
    'Mexico' => 'Mexican',
    'Mongolia' => 'Mongolian',
    'Morocco' => 'Moroccan',
    'Mozambique' => 'Mozambican',
    'Namibia' => 'Namibian',
    'Nepal' => 'Nepalese',
    'Netherlands' => 'Dutchman',
    'New Zealand' => 'New Zealander',
    'Nicaragua' => 'Nicaraguan',
    'Nigeria' => 'Nigerian',
    'Norway' => 'Norwegian',
    'Oman' => 'Omani',
    'Pakistan' => 'Pakistani',
    'Panama' => 'Panamanian',
    'Paraguay' => 'Paraguayan',
    'Peru' => 'Peruvian',
    'Philippines' => 'Filipino',
    'Poland' => 'Pole',
    'Portugal' => 'Portuguese person',
    'Saudi Arabia' => 'Saudi',
    'Scotland' => 'Scot',
    'Senegal' => 'Senegalese person',
    'Serbia' => 'Serbian',
    'Singapore' => 'Singaporean',
    'Slovakia' => 'Slovak',
    'South Africa' => 'South African',
    'South Korea' => 'Korean',
    'Spain' => 'Spaniard',
    'Sri Lanka' => 'Sri Lankan',
    'Sudan' => 'Sudanese person',
    'Sweden' => 'Swede',
    'Switzerland' => 'Swiss person',
    'Syria' => 'Syrian',
    'Taiwan' => 'Taiwanese person',
    'Tajikistan' => 'Tajikistani',
    'Thailand' => 'Thai person',
    'Tonga' => 'Tongan',
    'Tunisia' => 'Tunisian',
    'Turkey' => 'Turk',
    'Ukraine' => 'Ukrainian',
    'United Arab Emirates' => 'Emirati',
    'United Kingdom' => 'Briton',
    'United States' => 'American',
    'Uruguay' => 'Uruguayan',
    'Venezuela' => 'Venezuelan',
    'Vietnam' => 'Vietnamese person',
    'Wales' => 'Welshman',
    'Zambia' => 'Zambian',
    'Zimbabwe' => 'Zimbabwean'
    ];

function nation($nationality){
    echo $nationality." nationality is ";
    return NATIONALITY[$nationality].'<br>';
}
echo nation('Poland');
echo nation('Japan');
echo nation('Denmark');
echo nation('Germany');
echo nation('United States');